services:
  petpal_backend:
    image: petpal_backend
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - golden-network
    container_name: petpal_backend
    restart: unless-stopped
    ports:
      - 8080:8080
  ga_db:
    image: mongo
    container_name: ga-mongo_db
    restart: unless-stopped
    networks:
      - golden-network
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=inwza
      - MONGO_INITDB_ROOT_PASSWORD=strongpassword
    volumes:
      - mongo_local_temp:/data/db
  ga_db-client:
    image: mongo-express
    restart: unless-stopped
    networks:
      - golden-network
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=inwza
      - ME_CONFIG_MONGODB_ADMINPASSWORD=strongpassword
      - ME_CONFIG_MONGODB_URL=mongodb://inwza:strongpassword@ga_db:27017/
    depends_on:
      - ga_db
volumes:
  mongo_local_temp:
networks:
  golden-network:
